CREATE TABLE B1.TestDbSequenceIds(
	DbSequenceId BIGINT IDENTITY(1,1) NOT NULL,
	Remarks NVARCHAR(100) NULL,
 CONSTRAINT TestDbSequenceIds_PK PRIMARY KEY NONCLUSTERED 
(
	DbSequenceId ASC
) ON B1CoreIdx
) ON B1Core
GO
