--
-- This table is used for testing and demoing the functionality
-- of the DataAccessMgr class and the UniqueIds table and stored procedure.
--  
CREATE TABLE B1.TestSequence(
  AppSequenceId BIGINT NOT NULL,	-- unique id generated by DataAccessMgr
  DbSequenceId BIGINT IDENTITY(1,1) NOT NULL, -- unique id generated by database 
  AppSynchTime DATETIME NOT NULL, -- application-database synchronized time kept by app
  AppLocalTime DATETIME NOT NULL, -- local time of application
  DbServerTime DATETIME DEFAULT(GETUTCDATE()) NOT NULL, -- database server time (universal time)
  AppSequenceName NVARCHAR(32) not null, -- sample name field
  Remarks NVARCHAR(100), -- sample comments
  ExtraData NVARCHAR(MAX) -- sample large data field
 CONSTRAINT SequenceTest_PK_AppSequenceId PRIMARY KEY(AppSequenceId)
) ON B1Core
GO

CREATE UNIQUE INDEX TestSequence_UX_DbSequenceId_AppSequenceId ON
	B1.TestSequence( DbSequenceId, AppSequenceId ) ON B1CoreIdx
GO

CREATE UNIQUE INDEX TestSequence_UX_AppSequenceName_AppSequenceId ON
B1.TestSequence( AppSequenceName, AppSequenceId ) ON B1CoreIdx
GO
