--
-- This table is used for testing and demoing the functionality
-- of the DataAccessMgr class and the UniqueIds table and stored procedure.
--  
CREATE TABLE B1.TestSequence(
  AppSequenceId bigint NOT NULL,	-- unique id generated by DataAccessMgr
  DbSequenceId bigint identity(1,1) NOT NULL, -- unique id generated by database 
  AppSynchTime datetime not null, -- application-database synchronized time kept by app
  AppLocalTime datetime not null, -- local time of application
  DbServerTime datetime DEFAULT(getutcdate()) not null, -- database server time (universal time)
  AppSequenceName varchar(32) not null, -- sample name field
  Remarks varchar(100), -- sample comments
  ExtraData varchar(max) -- sample large data field
 CONSTRAINT PK_SequenceTest_AppSequenceId PRIMARY KEY(AppSequenceId)
) ON B1Core
go
create unique index UX_TestSequence_DbSequenceId_AppSequenceId on
B1.TestSequence( DbSequenceId, AppSequenceId ) ON B1CoreIdx
create unique index UX_TestSequence_AppSequenceName_AppSequenceId on
B1.TestSequence( AppSequenceName, AppSequenceId ) ON B1CoreIdx
go
grant references on B1.TestSequence to public
go
grant insert, update, delete, select on B1.TestSequence to public
go