//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

namespace B1.Data.Models
{
    public partial class B1SampleEntities : ObjectContext
    {
        public const string ConnectionString = "name=B1SampleEntities";
        public const string ContainerName = "B1SampleEntities";
    
        #region Constructors
    
        public B1SampleEntities()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public B1SampleEntities(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public B1SampleEntities(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<AppMaster> AppMasters
        {
            get { return _appMasters  ?? (_appMasters = CreateObjectSet<AppMaster>("AppMasters")); }
        }
        private ObjectSet<AppMaster> _appMasters;
    
        public ObjectSet<AppSession> AppSessions
        {
            get { return _appSessions  ?? (_appSessions = CreateObjectSet<AppSession>("AppSessions")); }
        }
        private ObjectSet<AppSession> _appSessions;
    
        public ObjectSet<SignonControl> SignonControls
        {
            get { return _signonControls  ?? (_signonControls = CreateObjectSet<SignonControl>("SignonControls")); }
        }
        private ObjectSet<SignonControl> _signonControls;
    
        public ObjectSet<UserMaster> UserMasters
        {
            get { return _userMasters  ?? (_userMasters = CreateObjectSet<UserMaster>("UserMasters")); }
        }
        private ObjectSet<UserMaster> _userMasters;
    
        public ObjectSet<UserSession> UserSessions
        {
            get { return _userSessions  ?? (_userSessions = CreateObjectSet<UserSession>("UserSessions")); }
        }
        private ObjectSet<UserSession> _userSessions;
    
        public ObjectSet<TestSequence> TestSequences
        {
            get { return _testSequences  ?? (_testSequences = CreateObjectSet<TestSequence>("TestSequences")); }
        }
        private ObjectSet<TestSequence> _testSequences;

        #endregion
    }
}
