//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace B1.Data.Models
{
    public partial class AppSession
    {
        #region Primitive Properties
    
        public virtual int AppCode
        {
            get { return _appCode; }
            set
            {
                if (_appCode != value)
                {
                    if (AppMaster != null && AppMaster.AppCode != value)
                    {
                        AppMaster = null;
                    }
                    _appCode = value;
                }
            }
        }
        private int _appCode;
    
        public virtual string AppId
        {
            get;
            set;
        }
    
        public virtual string AppProduct
        {
            get;
            set;
        }
    
        public virtual string AppVersion
        {
            get;
            set;
        }
    
        public virtual long MultipleSessionCode
        {
            get;
            set;
        }
    
        public virtual string MachineName
        {
            get;
            set;
        }
    
        public virtual long ProcessId
        {
            get;
            set;
        }
    
        public virtual System.DateTime StartDateTime
        {
            get;
            set;
        }
    
        public virtual System.DateTime StatusDateTime
        {
            get;
            set;
        }
    
        public virtual string EnvironmentSettings
        {
            get;
            set;
        }
    
        public virtual string ConfigSettings
        {
            get;
            set;
        }
    
        public virtual string StatusMessage
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual AppMaster AppMaster
        {
            get { return _appMaster; }
            set
            {
                if (!ReferenceEquals(_appMaster, value))
                {
                    var previousValue = _appMaster;
                    _appMaster = value;
                    FixupAppMaster(previousValue);
                }
            }
        }
        private AppMaster _appMaster;

        #endregion
        #region Association Fixup
    
        private void FixupAppMaster(AppMaster previousValue)
        {
            if (previousValue != null && previousValue.AppSessions.Contains(this))
            {
                previousValue.AppSessions.Remove(this);
            }
    
            if (AppMaster != null)
            {
                if (!AppMaster.AppSessions.Contains(this))
                {
                    AppMaster.AppSessions.Add(this);
                }
                if (AppCode != AppMaster.AppCode)
                {
                    AppCode = AppMaster.AppCode;
                }
            }
        }

        #endregion
    }
}
