//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace B1.Data.Models
{
    public partial class TestSequence
    {
        #region Primitive Properties
    
        public virtual long AppSequenceId
        {
            get;
            set;
        }
    
        public virtual long DbSequenceId
        {
            get;
            set;
        }
    
        public virtual System.DateTime AppSynchTime
        {
            get;
            set;
        }
    
        public virtual System.DateTime AppLocalTime
        {
            get;
            set;
        }
    
        public virtual System.DateTime DbServerTime
        {
            get;
            set;
        }
    
        public virtual string AppSequenceName
        {
            get;
            set;
        }
    
        public virtual string Remarks
        {
            get;
            set;
        }
    
        public virtual string ExtraData
        {
            get;
            set;
        }

        #endregion
    }
}
