//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace B1.Data.Models
{
    public partial class UserSession
    {
        #region Primitive Properties
    
        public virtual long SessionCode
        {
            get;
            set;
        }
    
        public virtual int UserCode
        {
            get { return _userCode; }
            set
            {
                if (_userCode != value)
                {
                    if (UserMaster != null && UserMaster.UserCode != value)
                    {
                        UserMaster = null;
                    }
                    _userCode = value;
                }
            }
        }
        private int _userCode;
    
        public virtual string UserId
        {
            get;
            set;
        }
    
        public virtual System.DateTime SignonDateTime
        {
            get;
            set;
        }
    
        public virtual System.DateTime SessionDateTime
        {
            get;
            set;
        }
    
        public virtual bool ForceSignoff
        {
            get;
            set;
        }
    
        public virtual int AppCode
        {
            get;
            set;
        }
    
        public virtual string AppId
        {
            get;
            set;
        }
    
        public virtual string AppVersion
        {
            get;
            set;
        }
    
        public virtual string AppMachine
        {
            get;
            set;
        }
    
        public virtual string RemoteAddress
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual UserMaster UserMaster
        {
            get { return _userMaster; }
            set
            {
                if (!ReferenceEquals(_userMaster, value))
                {
                    var previousValue = _userMaster;
                    _userMaster = value;
                    FixupUserMaster(previousValue);
                }
            }
        }
        private UserMaster _userMaster;

        #endregion
        #region Association Fixup
    
        private void FixupUserMaster(UserMaster previousValue)
        {
            if (previousValue != null && previousValue.UserSessions.Contains(this))
            {
                previousValue.UserSessions.Remove(this);
            }
    
            if (UserMaster != null)
            {
                if (!UserMaster.UserSessions.Contains(this))
                {
                    UserMaster.UserSessions.Add(this);
                }
                if (UserCode != UserMaster.UserCode)
                {
                    UserCode = UserMaster.UserCode;
                }
            }
        }

        #endregion
    }
}
