//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace B1.Utility.DatabaseSetup.ModelsSecond
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class SampleDbSecondContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new SampleDbSecondContainer object using the connection string found in the 'SampleDbSecondContainer' section of the application configuration file.
        /// </summary>
        public SampleDbSecondContainer() : base("name=SampleDbSecondContainer", "SampleDbSecondContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SampleDbSecondContainer object.
        /// </summary>
        public SampleDbSecondContainer(string connectionString) : base(connectionString, "SampleDbSecondContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SampleDbSecondContainer object.
        /// </summary>
        public SampleDbSecondContainer(EntityConnection connection) : base(connection, "SampleDbSecondContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TestSequence> TestSequences
        {
            get
            {
                if ((_TestSequences == null))
                {
                    _TestSequences = base.CreateObjectSet<TestSequence>("TestSequences");
                }
                return _TestSequences;
            }
        }
        private ObjectSet<TestSequence> _TestSequences;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<AppConfigParameter> AppConfigParameters
        {
            get
            {
                if ((_AppConfigParameters == null))
                {
                    _AppConfigParameters = base.CreateObjectSet<AppConfigParameter>("AppConfigParameters");
                }
                return _AppConfigParameters;
            }
        }
        private ObjectSet<AppConfigParameter> _AppConfigParameters;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TestSequences EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTestSequences(TestSequence testSequence)
        {
            base.AddObject("TestSequences", testSequence);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the AppConfigParameters EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAppConfigParameters(AppConfigParameter appConfigParameter)
        {
            base.AddObject("AppConfigParameters", appConfigParameter);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SampleDbSecond", Name="AppConfigParameter")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class AppConfigParameter : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new AppConfigParameter object.
        /// </summary>
        /// <param name="parameterName">Initial value of the ParameterName property.</param>
        /// <param name="parameterValue">Initial value of the ParameterValue property.</param>
        public static AppConfigParameter CreateAppConfigParameter(global::System.String parameterName, global::System.String parameterValue)
        {
            AppConfigParameter appConfigParameter = new AppConfigParameter();
            appConfigParameter.ParameterName = parameterName;
            appConfigParameter.ParameterValue = parameterValue;
            return appConfigParameter;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ParameterName
        {
            get
            {
                return _ParameterName;
            }
            set
            {
                if (_ParameterName != value)
                {
                    OnParameterNameChanging(value);
                    ReportPropertyChanging("ParameterName");
                    _ParameterName = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ParameterName");
                    OnParameterNameChanged();
                }
            }
        }
        private global::System.String _ParameterName;
        partial void OnParameterNameChanging(global::System.String value);
        partial void OnParameterNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ParameterValue
        {
            get
            {
                return _ParameterValue;
            }
            set
            {
                OnParameterValueChanging(value);
                ReportPropertyChanging("ParameterValue");
                _ParameterValue = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ParameterValue");
                OnParameterValueChanged();
            }
        }
        private global::System.String _ParameterValue;
        partial void OnParameterValueChanging(global::System.String value);
        partial void OnParameterValueChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SampleDbSecond", Name="TestSequence")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TestSequence : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TestSequence object.
        /// </summary>
        /// <param name="appSequenceId">Initial value of the AppSequenceId property.</param>
        /// <param name="dbSequenceId">Initial value of the DbSequenceId property.</param>
        /// <param name="appSynchTime">Initial value of the AppSynchTime property.</param>
        /// <param name="appLocalTime">Initial value of the AppLocalTime property.</param>
        /// <param name="dbServerTime">Initial value of the DbServerTime property.</param>
        /// <param name="appSequenceName">Initial value of the AppSequenceName property.</param>
        public static TestSequence CreateTestSequence(global::System.Int64 appSequenceId, global::System.Int64 dbSequenceId, global::System.DateTime appSynchTime, global::System.DateTime appLocalTime, global::System.DateTime dbServerTime, global::System.String appSequenceName)
        {
            TestSequence testSequence = new TestSequence();
            testSequence.AppSequenceId = appSequenceId;
            testSequence.DbSequenceId = dbSequenceId;
            testSequence.AppSynchTime = appSynchTime;
            testSequence.AppLocalTime = appLocalTime;
            testSequence.DbServerTime = dbServerTime;
            testSequence.AppSequenceName = appSequenceName;
            return testSequence;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 AppSequenceId
        {
            get
            {
                return _AppSequenceId;
            }
            set
            {
                if (_AppSequenceId != value)
                {
                    OnAppSequenceIdChanging(value);
                    ReportPropertyChanging("AppSequenceId");
                    _AppSequenceId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AppSequenceId");
                    OnAppSequenceIdChanged();
                }
            }
        }
        private global::System.Int64 _AppSequenceId;
        partial void OnAppSequenceIdChanging(global::System.Int64 value);
        partial void OnAppSequenceIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 DbSequenceId
        {
            get
            {
                return _DbSequenceId;
            }
            set
            {
                OnDbSequenceIdChanging(value);
                ReportPropertyChanging("DbSequenceId");
                _DbSequenceId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DbSequenceId");
                OnDbSequenceIdChanged();
            }
        }
        private global::System.Int64 _DbSequenceId;
        partial void OnDbSequenceIdChanging(global::System.Int64 value);
        partial void OnDbSequenceIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime AppSynchTime
        {
            get
            {
                return _AppSynchTime;
            }
            set
            {
                OnAppSynchTimeChanging(value);
                ReportPropertyChanging("AppSynchTime");
                _AppSynchTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AppSynchTime");
                OnAppSynchTimeChanged();
            }
        }
        private global::System.DateTime _AppSynchTime;
        partial void OnAppSynchTimeChanging(global::System.DateTime value);
        partial void OnAppSynchTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime AppLocalTime
        {
            get
            {
                return _AppLocalTime;
            }
            set
            {
                OnAppLocalTimeChanging(value);
                ReportPropertyChanging("AppLocalTime");
                _AppLocalTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AppLocalTime");
                OnAppLocalTimeChanged();
            }
        }
        private global::System.DateTime _AppLocalTime;
        partial void OnAppLocalTimeChanging(global::System.DateTime value);
        partial void OnAppLocalTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DbServerTime
        {
            get
            {
                return _DbServerTime;
            }
            set
            {
                OnDbServerTimeChanging(value);
                ReportPropertyChanging("DbServerTime");
                _DbServerTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DbServerTime");
                OnDbServerTimeChanged();
            }
        }
        private global::System.DateTime _DbServerTime;
        partial void OnDbServerTimeChanging(global::System.DateTime value);
        partial void OnDbServerTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AppSequenceName
        {
            get
            {
                return _AppSequenceName;
            }
            set
            {
                OnAppSequenceNameChanging(value);
                ReportPropertyChanging("AppSequenceName");
                _AppSequenceName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AppSequenceName");
                OnAppSequenceNameChanged();
            }
        }
        private global::System.String _AppSequenceName;
        partial void OnAppSequenceNameChanging(global::System.String value);
        partial void OnAppSequenceNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Remarks
        {
            get
            {
                return _Remarks;
            }
            set
            {
                OnRemarksChanging(value);
                ReportPropertyChanging("Remarks");
                _Remarks = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Remarks");
                OnRemarksChanged();
            }
        }
        private global::System.String _Remarks;
        partial void OnRemarksChanging(global::System.String value);
        partial void OnRemarksChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ExtraData
        {
            get
            {
                return _ExtraData;
            }
            set
            {
                OnExtraDataChanging(value);
                ReportPropertyChanging("ExtraData");
                _ExtraData = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ExtraData");
                OnExtraDataChanged();
            }
        }
        private global::System.String _ExtraData;
        partial void OnExtraDataChanging(global::System.String value);
        partial void OnExtraDataChanged();

        #endregion
    
    }

    #endregion
    
}
