--------------------------------------------------------
--  DDL for Table TESTDBSEQUENCEIDS
--------------------------------------------------------

  CREATE TABLE "B1"."TESTDBSEQUENCEIDS" 
   (	"DBSEQUENCEID" NUMBER(19,0), 
	"REMARKS" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "B1CORE" ;
  
grant references on B1.TestSequence to public
/
grant all on B1.TestSequence to public
/

--------------------------------------------------------
--  DDL for Sequence DBSEQUENCEID_SEQ
--------------------------------------------------------

 CREATE SEQUENCE  "B1"."TESTDBSEQUENCEID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;

   
--------------------------------------------------------
--  DDL for Index TABLE1_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "B1"."TABLE1_PK" ON "B1"."TESTDBSEQUENCEIDS" ("DBSEQUENCEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "B1CORE" ;
--------------------------------------------------------
--  Constraints for Table TESTDBSEQUENCEIDS
--------------------------------------------------------

  ALTER TABLE "B1"."TESTDBSEQUENCEIDS" MODIFY ("DBSEQUENCEID" NOT NULL ENABLE);
 
  ALTER TABLE "B1"."TESTDBSEQUENCEIDS" ADD CONSTRAINT "TABLE1_PK" PRIMARY KEY ("DBSEQUENCEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "B1CORE"  ENABLE;
--------------------------------------------------------
--  DDL for Trigger TESTDBSEQUENCEID_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "B1"."TESTDBSEQUENCEID_TRG" BEFORE INSERT ON B1.TESTDBSEQUENCEIDS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.DBSEQUENCEID IS NULL THEN
      SELECT TESTDBSEQUENCEID_SEQ.NEXTVAL INTO :NEW.DBSEQUENCEID FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "B1"."TESTDBSEQUENCEID_TRG" ENABLE;
