--
-- This table is used for testing and demoing the functionality
-- of the DataAccessMgr class and the UniqueIds table and stored procedure.
--  
CREATE TABLE B1.TestSequence(
  AppSequenceId number(19) NOT NULL,	-- unique id generated by DataAccessMgr
  DbSequenceId number(19) NOT NULL,-- unique id generated by database 
  AppSynchTime date not null,-- application-database synchronized time kept by app
  AppLocalTime date not null,-- local time of application
  DbServerTime timestamp DEFAULT(sys_extract_utc(systimestamp)) not null,-- database server time (universal time)
  AppSequenceName varchar2(32) not null, -- sample name field
  Remarks varchar2(100),-- sample comments
  ExtraData clob,-- sample large data field
 CONSTRAINT PK_TestSequence_AppSequenceId PRIMARY KEY(AppSequenceId)
) tablespace B1Core
/
create unique index B1.UX_TestSequence_Name_Id on
B1.TestSequence( NLSSORT(AppSequenceName, 'NLS_SORT=BINARY_CI' ), AppSequenceId ) tablespace B1CoreIdx
/
grant references on B1.TestSequence to public
/
grant all on B1.TestSequence to public
/
-- sequence for the dbSequenceId column
create sequence B1.DbSequenceId_Seq
start with 1
increment by 1
cache 20
-- NOTE: YOU MUST END THIS FILE WITH THE SLASH OR COMMAND LINE SQLPLUS WILL HANG WAITING FOR COMMAND INPUT
/