--#SET TERMINATOR /

ATTACH to NDEAE9A5 user Administrator using Sprint123
/
-- Drop database 
DROP DATABASE R1SAMPLE
/
-- Create a sample database
CREATE DATABASE R1SAMPLE AUTOMATIC STORAGE YES ON 'C:'
/
UPDATE DB CFG FOR R1SAMPLE USING AUTO_MAINT ON
/
UPDATE DB CFG FOR R1SAMPLE USING AUTO_TBL_MAINT ON
/
UPDATE DB CFG FOR R1SAMPLE USING AUTO_RUNSTATS ON
/
UPDATE ALERT CFG FOR DATABASE ON R1SAMPLE USING db.db_backup_req SET THRESHOLDSCHECKED YES
/
UPDATE ALERT CFG FOR DATABASE ON R1SAMPLE USING db.tb_reorg_req SET THRESHOLDSCHECKED YES
/
UPDATE ALERT CFG FOR DATABASE ON R1SAMPLE USING db.tb_runstats_req SET THRESHOLDSCHECKED YES
/
-- connect to the database using the default userid used when db2 was installed
CONNECT TO R1SAMPLE user Administrator using Sprint123 
/
-- create sample tablespaces on database (for tables)
CREATE  REGULAR  TABLESPACE B1CORE PAGESIZE 4 K  MANAGED BY AUTOMATIC STORAGE 
EXTENTSIZE 16 OVERHEAD 10.5 PREFETCHSIZE 16 TRANSFERRATE 0.14 BUFFERPOOL  IBMDEFAULTBP  DROPPED TABLE RECOVERY ON
/
-- create sample tablespaces on database (for indexes)
CREATE  REGULAR  TABLESPACE B1COREIDX PAGESIZE 4 K  MANAGED BY AUTOMATIC STORAGE 
EXTENTSIZE 16 OVERHEAD 10.5 PREFETCHSIZE 16 TRANSFERRATE 0.14 BUFFERPOOL  IBMDEFAULTBP  DROPPED TABLE RECOVERY ON
/
-- create the B1 schema for the database objects
CREATE SCHEMA B1 AUTHORIZATION ADMINISTRATOR
/
